Update format.yml
I think I got it this time

diff --git a/.github/workflows/format.yml b/.github/workflows/format.yml
--- a/.github/workflows/format.yml
+++ b/.github/workflows/format.yml
@@ -18,26 +18,23 @@ jobs:
     # Step 3: Run clang-format in check mode
     - name: Run clang-format
       run: |
-      for FILE in **/*.cpp; do
-      	  TEMP_FILE=$(mktemp)
-
-    	  clang-format --style=Google "$FILE" > "$TEMP_FILE"
-
-    	  if ! diff -q "$FILE" "$TEMP_FILE" >/dev/null 2>&1; then
-	  exit 1 
+        # Run clang-format on each file and check if it needs formatting
+        for FILE in backend/src/*.cpp ; do
+          clang-format --style=Google "${FILE}" > formatted_file
+          
+          # Compare the original file and the formatted output
+          if ! cmp -s "${file}" formatted_file; then
+            echo "::error file=$file::File is not formatted correctly."
+            exit 1
           fi
+        done
 
-          rm "$TEMP_FILE"
-      done
-
-      for FILE in **/*.h; do
-      	  TEMP_FILE=$(mktemp)
-
-      	  clang-format --style=Google "$FILE" > "$TEMP_FILE"
-
-    	  if ! diff -q "$FILE" "$TEMP_FILE" >/dev/null 2>&1; then
-	  exit 1
+        for FILE in backend/src/*.h ; do
+          clang-format --style=Google "${FILE}" > formatted_file
+          
+          # Compare the original file and the formatted output
+          if ! cmp -s "${file}" formatted_file; then
+            echo "::error file=$file::File is not formatted correctly."
+            exit 1
           fi
-
-    	  rm "$TEMP_FILE"
-      done
+        done
